domain: https://discordbots.co.uk
baseurl: ""
url: https://discordbots.co.uk
encoding: utf-8

plugins:
  - jekyll-sitemap

include: 
  - _pages
  - _pages/api
  - _pages/api/bots
  - _pages/api/servers

sass:
  sass_dir: _sass
  style: compressed

collections:
  docs:
    output: true
    permalink: /:collection/:name/
  bots:
    output: true
    permalink: /:collection/:name/
  servers:
    output: true
    permalink: /:collection/:name/
  bans:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: item
      type: docs
      layout: docs
  - scope:
      path: ""
      type: bots
    values:
      layout: item
      type: bots
  - scope:
      path: ""
      type: servers
    values:
      layout: item
      type: servers
  - scope:
      path: ""
      type: bans
    values:
      layout: item
      type: bans
